### ISSUE TITLE
Error occurred when I ran docqa

### ISSUE THREAD

**Issue by directv00** [naver/claf#5]
Hi, all,
After download docker image and get ready,  I found myself got an error when I ran docqa.
See below.
...
Completed!
Ready ..!

Question > 동학의 2대 교주 이름은?
Traceback (most recent call last):
  File "machine.py", line 22, in <module>
    answer = claf_machine.get_answer(question)
AttributeError: 'OpenQA' object has no attribute 'get_answer'

Could you give me a clue to get through?

**Comment by DongjunLee** [comment]
Oh, That's my mistake.

There will be no problem if you edit the code like below.

- before
```python
answer = claf_machine.get_answer(question) 
```

- after
```python
answer = claf_machine(question)
```

**Comment by directv00** [comment]
After edit and run, I got an another error after calculating doc scores,
---------------------------------------------------------------------------------------------------
Completed!
Ready ..!
Question > 동학의 2대 교주 이름은?
--------------------------------------------------
Doc Scores:
 - 교주 : 0.5337303876876831
 - 교주도 : 0.4840213656425476
 - 동학 : 0.4764273464679718
 - 이름 : 0.3633122742176056
 - 작은 수의 이름 : 0.33019009232521057
--------------------------------------------------
Traceback (most recent call last):
  File "machine.py", line 22, in <module>
    answer = claf_machine(question)
  File "/workspace/claf/claf/machine/open_qa.py", line 100, in __call__
    answer_text = self.machine_reading(passage, question)
  File "/workspace/claf/claf/machine/open_qa.py", line 111, in machine_reading
    return self.rc_experiment.predict(raw_feature)
  File "/workspace/claf/claf/learn/experiment.py", line 428, in predict
    interactive=arguments.get("interactive", False),
  File "/workspace/claf/claf/learn/trainer.py", line 536, in predict
    output_dict = self.model(tensor_feature)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/claf/claf/model/reading_comprehension/docqa.py", line 210, in forward
    context_self_attnded = self.self_attention(context_encoded, context_mask)  # B X C_L X dim*2
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/claf/claf/model/reading_comprehension/docqa.py", line 273, in forward
    context_self_attnded = self.self_attention(context, context_mask, context, context_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/claf/claf/modules/attention/docqa_attention.py", line 46, in forward
    diag_mask = self.diag_mask.narrow(0, 0, seq_length).narrow(1, 0, seq_length)
RuntimeError: start (0) + length (5769) exceeds dimension size (2000).

**Comment by DongjunLee** [comment]
Each document has a different length of paragraph.
Some paragraphs will be very long.

`DocQA`'s `max_sequence_length` is fixed 2000.  
([claf.modules.attention.docqa_attention.py](https://github.com/naver/claf/blob/master/claf/modules/attention/docqa_attention.py#L35))

**Comment by directv00** [comment]
Is it possible to change max_sequence_length to bigger one?
When I set 10000, it gave an error that seemed to be a size problem.

**Comment by DongjunLee** [comment]
It is possible, but you will have to re-trainining it to use.
